### ISSUE TITLE
Support MacOS

### ISSUE THREAD

**Issue by sorawee** [dbenoit17/dynamic-ffi#28]
I just got `dynamic-ffi` to work with MacOS, but there are various hacks that I needed to add. It would be nice if `dynamic-ffi`  works out of the box.

First, MacOS can install llvm fine, so `(clang++-exists?)` and `(clang-headers-exist?)` return `#t` [as expected](https://github.com/dbenoit17/dynamic-ffi/blob/master/make.rkt#L144). However, MacOS doesn't have (and doesn't need) `ldconfig`, so the last check will always fail. I workaround this by creating a dummy `ldconfig` that `echo libclang`. It's horrendous, but allow me to get past the setup process. It would be nice if this check is skipped if MacOS is detected.

Second, I tried 

```
(define-inline-ffi mylib
  "int add(int x, int y) {"
  "  return x + y;"
  "}")
 
(mylib 'add 3 4)
```

and got an error that `~/Library/Racket/7.5/pkgs/dynamic-ffi/compiled/ffi-cache/mylib.a184d8fed9b6151bd03fc639e9e085ffa9111d58.rkt.c.dylib` is not found (`.dylib` is `.so`-equivalent in MacOS). It turns out that this file in fact exists, but has `.so` file extension instead. Renaming `.so` -> `.dylib` allows the program to run fine. I think the fix is to change [this line](https://github.com/dbenoit17/dynamic-ffi/blob/master/inline.rkt#L28) to use `(system-type 'so-suffix)` instead.

**Comment by dbenoit17** [comment]
@sorawee Thanks very much for doing this.  Great work on this and the docs.

**Comment by sorawee** [comment]
My pleasure :) Thanks for your hard work on this library too!
