### ISSUE TITLE
generate-static-ffi: check for undefined symbol automatically

### ISSUE THREAD

**Issue by sorawee** [dbenoit17/dynamic-ffi#31]
As I understand, it should be possible to run `get-ffi-obj` and see if a symbol is defined at code generation time, correct? It should then be possible to omit symbols that are undefined.

**Comment by dbenoit17** [comment]
This is a cool idea, but it also adds a dependency on the object-files being present to generate the FFI definitions.  Currently, one should in theory be able to generate FFI definitions from header files alone.

I think I would prefer to implement this as a switch using a keyword argument, so the current behavior remains the default, but users can opt in to such a lookup at code-generation time.
